# Generated by Django 3.2.6 on 2021-12-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='work_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
